apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
     app: webapp

spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp

  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: 241533119861.dkr.ecr.ap-south-1.amazonaws.com/milestone-3-repository:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
